#import "./GroupFragments.gql"

mutation JoinGroup($user_id:uuid!, $group_id:uuid!){
  membership: insert_group_member_one(object:{
    user_id:$user_id,
    group_id:$group_id
  }){
    id
    group {
      ...GroupDetail
    }
  }
}
