#import "./PostFragment.gql"

mutation DeletePostReaction($post_id: uuid!, $user_id: uuid!) {
  delete_post_reaction(where: {post_id: {_eq: $post_id}, user_id: {_eq: $user_id}}) {
    returning {
      id
      post {
        ... PostSummary
      }
    }
  }
}
